// Chapter 1 — おはよう平原 (theme: 起きること).
// Roster mirrors docs/redesign/06-boss-design.md §3. Weakness/resist are derived
// from `element` via elements.ts, so this file only declares the affinity.

import type { EnemyDef } from './types';

export const CH01_ENEMIES: EnemyDef[] = [
  {
    id: 'nemukedama',
    name: 'ネムケダマ',
    tier: 'mob',
    chapter: 1,
    element: 'ma',
    hpTurns: 3,
    breakGauge: 0,
    attack: 5,
    agility: 8,
    critChance: 0.05,
    moves: [
      { id: 'tackle', kind: 'attack', weight: 3, power: 1, log: 'たいあたり!' },
      { id: 'drowse', kind: 'status', weight: 1, status: 'sleep', statusChance: 0.3, log: 'ねむけを とばしてきた!' },
    ],
    lore: 'あくびが服を着たようなダラモン。悪気は本当にない。',
    loreAfter: '朝の体操教室に通いはじめた。まだ半分ねぼけている。',
  },
  {
    id: 'makuragani',
    name: 'マクラガニ',
    tier: 'mob',
    chapter: 1,
    element: 'shu',
    hpTurns: 4,
    breakGauge: 0,
    attack: 6,
    agility: 5,
    critChance: 0.03,
    moves: [
      { id: 'pinch', kind: 'attack', weight: 3, power: 1, log: 'まくらで はさんできた!' },
      { id: 'harden', kind: 'buff', weight: 1, log: 'こうらに こもった!' },
    ],
    lore: '枕をなかなか返してくれないカニ。寝心地には こだわる。',
    loreAfter: '宿屋の枕係として就職。客の眠りは大陸いちと評判。',
  },
  {
    id: 'yumeusagi',
    name: 'ユメウサギ',
    tier: 'mob',
    chapter: 1,
    element: 'jin',
    hpTurns: 3,
    breakGauge: 0,
    attack: 4,
    agility: 13,
    critChance: 0.08,
    moves: [
      { id: 'hop', kind: 'attack', weight: 3, power: 0.9, log: 'ぴょんと とびかかった!' },
      { id: 'daydream', kind: 'debuff', weight: 1, log: 'ゆめを みせて まどわせた!' },
    ],
    lore: '夢の中を全力で走っているウサギ。とにかく素早い。',
    loreAfter: '朝いちばんの新聞配達員に。誰よりも早く走り回っている。',
  },
  {
    id: 'futon-golem',
    name: 'フトンゴーレム',
    tier: 'elite',
    chapter: 1,
    element: 'shu',
    hpTurns: 6,
    breakGauge: 4,
    attack: 9,
    agility: 6,
    critChance: 0.05,
    moves: [
      { id: 'slam', kind: 'attack', weight: 3, power: 1, log: 'ふとんで たたきつけた!' },
      { id: 'compress', kind: 'charge', weight: 2, condition: 'always', log: 'ふとんを あつく おりたたんでいる…' },
      { id: 'compress-hit', kind: 'unleash', weight: 0, power: 2.2, log: 'ふとんプレス!' },
      { id: 'cozy', kind: 'buff', weight: 1, log: 'ぬくもりで みをかためた!' },
    ],
    lore: '万年床が意思を持って立ち上がった姿。妙にあたたかい。',
    loreAfter: 'クリーニング店の看板娘(?)に転身。ふわふわに仕上げる。',
    quotes: { open: 'むにゃ……もう あさ?', defeat: 'ほし……ぱりっと したなあ……' },
  },
  {
    id: 'suyarin',
    name: 'まくら大公スヤリン',
    tier: 'lord',
    chapter: 1,
    element: 'ma',
    hpTurns: 10,
    breakGauge: 6,
    attack: 8,
    agility: 9,
    critChance: 0.1,
    phases: 2,
    moves: [
      { id: 'fluff', kind: 'attack', weight: 3, power: 1, log: 'もふっと たいあたり!' },
      { id: 'lullaby', kind: 'debuff', weight: 2, log: 'こもりうたで みんなを ねむくさせた!' },
      { id: 'drowse', kind: 'status', weight: 2, status: 'sleep', statusChance: 0.4, log: 'あまい ねむけが おそう!' },
      { id: 'rollover', kind: 'attack', weight: 2, power: 1.6, condition: 'phase2', log: 'ねがえり!ぜんたいに のしかかる!' },
    ],
    lore: '「あと5ふん」の化身。ふかふかの羊で、近づく者を二度寝させる。',
    loreAfter: '町いちばん早起きの目覚まし屋を開業。開店には毎日遅刻する。',
    quotes: {
      open: 'んん……いま いいとこ なんだけど……',
      phase2: 'もう ちょっとだけ……ねかせて!',
      defeat: 'えっ……もう あさ!? ……あさだ!',
    },
  },
];
